// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetPublicKey():Promise<string>;

export function SignData(arg1:string):Promise<string>;
