// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetPublicKey() {
  return window['go']['main']['App']['GetPublicKey']();
}

export function SignData(arg1) {
  return window['go']['main']['App']['SignData'](arg1);
}
